version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: bankCard
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bankCard
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  card:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: